version: '3.8'

services:
  estudios-panda:
    build: .
    container_name: estudios-panda-app
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - proxy
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=hitflow.com.ar
      - VIRTUAL_PATH=/estudios-panda
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=hitflow.com.ar
      - LETSENCRYPT_EMAIL=tu-email@dominio.com
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

networks:
  proxy:
    external: true

# Si necesitas volúmenes para logs o datos
volumes:
  app-data:
    driver: local
